% template for a new chapter
<<echo=FALSE>>=
source("Rprofile.R")
knitrSet("chXX")
.locals$chXX <- NULL
@

\chapter{}\label{ch:}
%\input{chXX/vtoc}		% visual table of contents

\chapterprelude{
}
% \minitoc
% \clearpage



% Cleanup local variables
<<cleanupXX, size='footnotesize'>>=
# detach(package:ggtern)  ## detach any masking packages
.locals$chXX <- setdiff(ls(), .globals)
.locals$chXX
remove(list=.locals$chXX[sapply(.locals$chXX,function(n){!is.function(get(n))})]) 

@


