\begin{Exercises}

  \exercise The \data{JobSat} data in \pkg{vcdExtra} gives a $4 \times 4$ table recording job satisfaction
  in relation to income.
  \begin{enumerate*}
    \item  Carry out a simple \ca on this table.  How much of the inertia is accounted for by a
    one-dimensional solution?  How much by a two-dimensional solution?
    \item Plot the 2D CA solution.  To what extent can you consider the association between
    job satisfaction and income ``explained'' by the ordinal nature of these variables?
  \end{enumerate*}
  
  \exercise Refer to Exercise 1 in \chref{ch:mosaic}.  Carry out a simple \ca on the
  $4 \times 5$ table \data{criminal} from the \Rpackage{logmult}.
  \begin{enumerate*}
    \item What percentages of the Pearson \chisq for association are explained
    by the various dimensions?
    \item Plot the 2D \ca solution. Describe the pattern of association between
    year and age.
  \end{enumerate*}
  
  \exercise The data set \data{caith} in \pkg{MASS} gives a classic table 
  tabulating hair color and eye color 
  of people in Caithness, Scotland, originally from
  \citet{Fisher:1940}.
  \begin{enumerate*}
    \item Carry out a simple \ca on this table.  How many dimensions
    seem necessary to account for most of the association in the table?
    \item Plot the 2D solution. The interpretation of the first dimension
    should be obvious; is there any interpretation for the second dimension?
  \end{enumerate*}
  
  \exercise The same data, plus a similar table for Aberdeen, are given as a
  three-way table as \data{HairEyePlace} in \pkg{vcdExtra}.
  \begin{enumerate*}
    \item Carry out similar \ca analysis to the last exercise 
    for the data from Aberdeen.  
    Comment on any differences in the
    placement of the category points.
    \item Analyze the three-way table, stacked to code hair color and
    place interactively, i.e., for the \loglin model $\LLM{Hair Place, Eye}$.
    What does this show?
  \end{enumerate*}
  
  \exercise For the mental health data analyzed in \exref{ex:mental3}, construct a shaded sieve diagram
  and mosaic plot. Compare these with the \ca plot shown in \figref{fig:ca-mental-plot}.  What features of
  the data and the association between SES and mental health status are shown in each?
  
  \exercise Simulated data is often useful to help understand the connections between data, analysis
  methods and associated graphic displays.
  \secref{sec:ca-interactiveR} illustrated interactive coding in \R, using a simulated 4-way table
  of counts of pets, classified by age, color and sex, but with no associations because the counts had
  a constant Poisson mean, $\lambda=15$. 
  \begin{enumerate*}
    \item Re-do this example, but in the call to \func{rpois}, specify
    a non-negative vector of Poisson means to create some associations among the table factors.
    \item Use CA methods to determine if and how the structure you created in the data appears in
    the results.
  \end{enumerate*}
  
  \exercise\label{lab:TV3} The \data{TV} data was analyzed using CA in \exref{ex:TV2}, ignoring the variable
  \var{Time}.  Carry out analyses of the 3-way table, reducing the number of levels of \var{Time}
  to three hourly intervals as shown below.
<<TV3>>=
data("TV", package="vcdExtra")
# reduce number of levels of Time
TV.df <- as.data.frame.table(TV)
levels(TV.df$Time) <- rep(c("8", "9", "10"), c(4, 4, 3))
TV3 <- xtabs(Freq ~ Day + Time + Network, TV.df)
structable(Day ~ Network + Time, TV3)
@
  \begin{enumerate*}
    \item Use the stacking approach (\secref{sec:ca-multiway}) to perform a CA of the table with
    \var{Network} and \var{Time} coded interactively. You can create this using the \func{as.matrix}
    method for a \class{structable} object.
<<TV3S, eval=FALSE>>=
TV3S <- as.matrix(structable(Day ~ Network + Time, TV3), sep=":")
@
    \item What \loglin model is analyzed by this approach?
    \item Plot the 2D solution.  Compare this to the CA plot of the two-way table in \figref{fig:TV-mosaic-ca}.
    \item Carry out an MCA analysis using \func{mjca} of the three-way table \code{TV3}.  Plot the 2D solution,
    and compare this with both the CA plot and the solution for the stacked three-way table.  
  \end{enumerate*}

 \exercise\label{lab:presex} Refer to the MCA analysis of the \data{PreSex} data in \exref{ex:marital3}.
   	  Use the stacking approach to analyze the stacked table with the combinations of 
  	  premarital and extramarital sex in the rows and the combinations of gender and marital status
  	  in the columns.  As suggested in the exercise above, you can use 
  	  \code{as.matrix(structable()} to create the stacked table

  \begin{enumerate*}
  	  \item What \loglin model is analyzed by this approach? Which associations are included and
  	  which are excluded in this analysis?
  	  \item Plot the 2D CA solution for this analysis.  You might want to draw lines connecting
  	  some of the row points or column points to aid in interpretation.
  	  \item How does this analysis differ from the MCA analysis shown in \figref{fig:presex-mca-plot}? 
  \end{enumerate*}
   
\end{Exercises}

