\begin{Exercises}

  \exercise Consider the data set \data{DaytonSurvey} (described in \exref{ex:dayton1}), giving
  results of a survey of use of alcohol (A), cigarettes (C), and marijuana (M) among high school
  seniors.  For this exercise, ignore the variables \var{sex} and \var{race}, by working with the
  marginal table \code{Dayton.ACM}, a $2 \times 2 \times 2$ table in frequency data frame form.
<<>>=
Dayton.ACM <- aggregate(Freq ~ cigarette + alcohol + marijuana, 
                        data=DaytonSurvey, FUN=sum)
@
  \begin{enumerate*}
  
    \item Use \func{loglm} to fit the model of mutual independence, \LLM{A,C,M}.
    \begin{ans}
    \end{ans}
    
    \item Prepare mosaic display(s) for associations among these variables.
    Give a verbal description of the association between cigarette and alcohol use.
    \begin{ans}
    \end{ans}
    
    \item Use \func{fourfold} to produce fourfold plots for each pair of variables,
    AC, AM, and CM, stratified by the remaining one.
    Describe these associations verbally.
    \begin{ans}
    \end{ans}
    
  \end{enumerate*}
  
  \exercise Continue the analysis of the \data{DaytonSurvey} data by fitting the following models:
  \begin{enumerate*}
    \item Joint independence, \LLM{AC,M}
    \begin{ans}
    \end{ans}
    
    \item Conditional independence, \LLM{AM,CM}
    \begin{ans}
    \end{ans}
    
    \item Homogeneous association, \LLM{AC,AM,CM}
    \begin{ans}
    \end{ans}
    
    \item Prepare a table giving the goodness-of-fit tests for these models, as well as the
    model of mutual independence, \LLM{A,C,M}, and the saturated model, \LLM{ACM}.
    \emph{Hint}: \func{anova} and \func{LRstats} are useful here.
    Which model appears to give the most reasonable fit?
    \begin{ans}
    \end{ans}
    
  \end{enumerate*}

  \exercise\label{lab:caesar-loglin} The data set \data{Caesar} in \pkg{vcdExtra} gives a $3 \times 2^3$ 
  frequency table
  classifying 251 women who gave birth by Caesarian section by \var{Infection} (three levels: none, Type 1, Type2)
  and \var{Risk}, whether \var{Antibiotics} were used,  and whether the Caesarian section was \var{Planned}
  or not. \var{Infection} is a natural response variable, but the table has quite a few zeros.
  \begin{enumerate*}
    \item Use \func{structable} and \func{mosaic} to see the locations of the zero cells in this table.
    \begin{ans}
    \end{ans}
    
    \item Use \func{loglm} to fit the baseline model \LLM{I, RAP}. Is there any problem due to 
    zero cells indicated in the output?
    \begin{ans}
    \end{ans}
    
    \item For the purpose of this excercise, treat all the zero cells as \emph{sampling zeros}
    by adding 0.5 to all cells, e.g., \code{Caesar1 <- Caesar + 0.5}.
    Refit the baseline model.
    \begin{ans}
    \end{ans}
    
    \item Now fit a ``main effects'' model \LLM{IR, IA, IP, RAP}
    that allows associations of \var{Infection} with each of
    the predictors.
    \begin{ans}
    \end{ans}
     
%     \item Assume that the \emph{structural zeros} in this table are those that occur when there is
%     no risk factor and the Caesarian section unplanned 
  \end{enumerate*}

  \exercise The \data{Detergent} in \pkg{vcdExtra} gives a $2^3 \times 3$ table classifying 
  a sample of 1,008 consumers according to their preference for  
  \begin{seriate}
    \item expressed \var{Preference} for Brand ``X'' or Brand ``M'' in a blind trial,
    \item \var{Temperature} of laundry water used,
    \item previous use (\var{M\_user}) of detergent Brand ``M,'' and
    \item the softness (\var{Water\_softness}) of the laundry water used.
  \end{seriate}
  \begin{enumerate*}
    \item Make some mosaic displays to visualize the associations among the table variables.  
    Try using different orderings of the table variables to make associations related to \var{Preference} more apparent.
    \begin{ans}
    \end{ans}
    
    \item Use a \func{doubledecker} plot to visualize how \var{Preference} relates to the other factors.
    \begin{ans}
    \end{ans}
    
    \item Use \func{loglm} to fit the baseline model \LLM{P,TMW} for \var{Preference} as the response variable.
    Use a mosaic display to visualize the lack of fit for this model.
    \begin{ans}
    \end{ans}
    
  \end{enumerate*}

%\TODO{Add more exercises}

%   \exercise \exref{ex:vision-glm} presented an analysis of the data on visual acuity 
%   for the subset of women in the \data{VisualAcuity} data.  Carry out a parallel
%   analysis of the models fit there for the \code{men} in this data set, given by:
% <<vision-men, eval=FALSE>>=
% data("VisualAcuity", package="vcd")
% men <- subset(VisualAcuity, gender=="male", select=-gender)
% @
% 
% 
%   \exercise \tabref{tab:birthcontrol} gives a $4 \times 4$ table of opinions about
%   premarital sex and whether methods of birth control should be made available
%   to teenagers aged 14--16 from the 1991 General Social Survey
%   \citep[Table 10.3]{Agresti:2013}.  Both variables are ordinal, and their
%   grades are represented by the case of the row and column labels.
% \input{ch09/tab/birthcontrol}
% 
%   \begin{enumerate*}
%     \item Fit the independence model to these data using \func{loglm} or \func{glm}.
%     \item Make a mosaic display showing departure from independence and describe
%     verbally the pattern of association.
%     \item Treating the categories as equally spaced, fit the $L \times L$ model
%     of uniform association, as in \secref{sec:loglin-ordinal}.  Test the
%     difference against the independence model with a \LR test.
%     \item Fit the RC(1) model with \func{gnm}, and test the difference of
%     this against the model of uniform association.
%     \item Write a brief summary of these results, including plots useful
%     for explaining the relationships in this data set.
%   \end{enumerate*}
%   
%   \exercise The data set \data{gss8590} in \pkg{logmult} gives a $4 \times 5 \times 4$
%   table of education levels and occupational categories for the four combinations
%   of gender and race from the General Social Surveys, 1985--1990 as reported by
%   \citet[Table 2]{Wong:2001}. \citet[Table 2.3B]{Wong:2010} later used the
%   subset pertaining to women to illustrate RC(2) models.  This data is
%   created below as \code{Women.tab}, correcting an inconsistency to conform with
%   the 2010 table.
%   
% 
% <<gss8590-1>>=
% data(gss8590, package="logmult")
% Women.tab <- margin.table(gss8590[,,c("White Women", "Black Women")], 1:2)
% Women.tab[2,4] <- 49
% colnames(Women.tab)[5] <- "Farm"
% @
%   \begin{enumerate*}
%     \item Fit the independence model, and also the RC(1) and RC(2) models using
%     \func{rc} with marginal weights, as illustrated in \exref{ex:mental6}.
%     Summarize these statistical tests in a table.
%     \item Plot the solution for the RC(2) model with 68\% confidence ellipses.
%     What verbal labels would you use for the two dimensions?
%     \item Is there any indication that a simpler model, using integer scores for
%     the row (Education) or column (Occupation) categories or both might suffice?
%     If so, fit the analogous column effects, row effects or $L \times L$ model,
%     and compare with the models fit in part (a).
%   \end{enumerate*}
% 

\end{Exercises}
